/** Per-window business state. Controllers receive this explicitly; there are no implicit script globals. */
export function createContext() {
    return {
        state: {
            page: 'chat',
            docs: [],
            snapshot: { },
            chatSignature: null,
            editorSyncError: null,
            selectedDocs: new Set(),
            selectedResources: new Map(),
            threadId: null,
            eventCursor: 0,
            currentDoc: null,
            lastMessage: new Map(),
            toolMessages: new Map(),
            modelSignature: '',
            updating: false,
            approvalQueue: new Map(),
            docDirty: false,
            documentRequest: 0,
            documentCache: new Map(),
            diffRequest: 0,
            editGeneration: 0,
            lastEditorDirty: null,
            editorSyncing: null,
            connectionRequests: { codex: null, unity: null },
            connectionAttempts: { codex: 0, unity: 0 },
            connectionErrors: { codex: '', unity: '' },
            reviewTasks: [],
            currentReview: null,
            reviewFile: null,
            reviewRequest: 0,
            reviewReading: null,
            lastReviewSync: 0,
            taskForChat: null,
            noteAnchor: null,
            reviewSummaryDirty: false,
            reviewNoteDirty: false,
            reviewFeedbackDirty: false,
            reviewSaving: false,
            reviewDraftGeneration: 0,
            workflowMode: 'discuss-requirement',
            restoringWorkspace: true,
            preferencesSaving: null,
            nextWorkspacePreferences: null,
            ruleSections: [['facts', '工程事实'], ['execution', '执行细则'], ['index', '项目索引'], ['templates', '模板']],
            extensionTools: [],
            selectedTool: null,
            settings: null,
            settingsDirty: false,
            graph: null,
            graphContextNodes: new Map(),
            toolRequest: 0,
            toolRunning: false
        },
        actions: { }
    };
}
